# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[(b'P', b'Primer'), (b'S', b'Segundo'), (b'T', b'Tercer')], default=0, max_length=1, verbose_name='Seleccione cohorte')),
            ],
            options={
                'db_table': 'cohorte',
                'verbose_name_plural': 'cohortes',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'notas',
                'verbose_name_plural': 'notas',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10, verbose_name=b'per\xc3\xadodo')),
                ('estatus', models.BooleanField()),
            ],
            options={
                'db_table': 'periodos',
                'verbose_name_plural': 'periodos',
            },
        ),
        migrations.CreateModel(
            name='PlanEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=100)),
                ('puntaje', models.CharField(blank=True, max_length=10, null=True)),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Cohorte')),
            ],
            options={
                'db_table': 'plan',
                'verbose_name_plural': 'planes',
            },
        ),
        migrations.AddField(
            model_name='notas',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.PlanEvaluacion'),
        ),
        migrations.AddField(
            model_name='notas',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Estudiantes'),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.Periodo'),
        ),
        migrations.AddField(
            model_name='cohorte',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Seccion'),
        ),
    ]
