# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=50, unique=True, verbose_name='N\xfamero de Identificaci\xf3n')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estudiantes',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asignatura', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'secciones',
                'verbose_name_plural': 'secciones',
            },
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Seccion'),
        ),
    ]
